### ISSUE TITLE
Windowsで「指定されたモジュールが見つかりません。c10.dll」と言われる。

### ISSUE THREAD

**Issue by darts-cloud** [darts-cloud/pose-estimate-webserver#2]
```
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
Traceback (most recent call last):
  File "C:\project\pose-estimate-webserver\main.py", line 1, in <module>
    import web_controller
  File "C:\project\pose-estimate-webserver\web_controller.py", line 4, in <module>
    from pose_estimate.analysis import *
  File "C:\project\pose-estimate-webserver\pose_estimate\analysis.py", line 2, in <module>
    from pose_estimate.model.yolo import *
  File "C:\project\pose-estimate-webserver\pose_estimate\model\yolo.py", line 3, in <module>
    from ultralytics import YOLO
  File "C:\project\pose-estimate-webserver\venv\Lib\site-packages\ultralytics\__init__.py", line 11, in <module>
    from ultralytics.models import NAS, RTDETR, SAM, YOLO, FastSAM, YOLOWorld
  File "C:\project\pose-estimate-webserver\venv\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .fastsam import FastSAM
  File "C:\project\pose-estimate-webserver\venv\Lib\site-packages\ultralytics\models\fastsam\__init__.py", line 3, in <module>
    from .model import FastSAM
  File "C:\project\pose-estimate-webserver\venv\Lib\site-packages\ultralytics\models\fastsam\model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "C:\project\pose-estimate-webserver\venv\Lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    import torch
  File "C:\project\pose-estimate-webserver\venv\Lib\site-packages\torch\__init__.py", line 262, in <module>
    _load_dll_libraries()
  File "C:\project\pose-estimate-webserver\venv\Lib\site-packages\torch\__init__.py", line 258, in _load_dll_libraries
    raise err
OSError: [WinError 126] 指定されたモジュールが見つかりません。 Error loading "C:\project\pose-estimate-webserver\venv\Lib\site-packages\torch\lib\c10.dll" or one of its dependencies.
```

**Comment by darts-cloud** [comment]
以下をインストールする必要があるようだ。
https://aka.ms/vs/17/release/vc_redist.x64.exe

参考：https://hamamuratakuo.hatenablog.com/entry/Stable-Diffusion-install
